[book]
authors = ["StarkWare"]
language = "zh"

src = "src"
title = "The Cairo Programming Language (Chinese)"
description = "Cairo Book 官方中文翻译版。全面介绍 Cairo 编程语言，涵盖基础语法、StarkNet 智能合约开发、Cairo VM 原理等内容。是学习 StarkNet 开发的权威指南。"

[output.html]
git-repository-url = "https://github.com/starkware-libs/cairo-book"
edit-url-template = "https://github.com/starkware-libs/cairo-book/edit/main/src/{path}"
